---
version: "3"

services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  redis:
    image: redis

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=aplikacija
